name: Model Training and Azure Storage

on:
  schedule:
    - cron: "0 2 * * 0"  # Run every Sunday at 2:00 AM UTC
  workflow_dispatch:  # Enable manual triggering
    inputs:
      message:
        description: 'Manual triggered run'
        required: false

jobs:
  train_model_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Your Azure CLI commands go here
            az --version

      - name: Download file from Azure Blob Storage
        run: |
          az storage blob download \
            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
            --container-name stock-prediction-data \
            --name StockPriceData.parquet \
            --file StockPriceDataWebScraped.parquet

      - name: Move file to data folder
        run: |
          mkdir -p src/data
          mv StockPriceDataWebScraped.parquet src/data/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tensorflow keras
          pip install --upgrade pandas scikit-learn

      - name: Execute Python script
        env:
          DATA_FOLDER: ${{ github.workspace }}/src/data
        run: python src/model_training.py

      - name: Upload trained models to Azure Blob Storage
        run: |
          az storage blob upload \
            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
            --container-name stock-price-models \
            --file src/models/* \
            --name trained_models \
            --overwrite
